# Permalinks
permalink:        pretty

# Setup
title:            Richard Huang
tagline:          Home
url:              http://richhx.github.io
paginate:         1
baseurl:          /
author:
  name:           Richard Huang
  email:          richhx@gmail.com

# Custom vars
version:          1.0.0
github:           
  repo:           https://github.com/richhx

pages_list:
  About: '/about'
  Archive: '/archive'
  Contact: '/contact'
  Feed: '/atom.xml'
  GitHub: 'https://github.com/richhx'
