# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Richard Huang
tagline:          Just A Normal Guy
url:              http://huangrichard.me
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:           
  repo:           https://github.com/richhx

pages_list:
  About: '/about'
  Archive: '/archive'
  Contact: '/contact'
  Feed: '/atom.xml'
  GitHub: 'https://github.com/richhx'
